CreateCVOnline/CreateCVOnline/Models/Candidate.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CreateCVOnline.Models
{
    public class Candidate
    {
        public string Username { get; set; }
        public string Fullname { get; set; }
        public string Age { get; set; }
        public string Image { get; set; }
        public string Email { get; set; }
    }
}

CreateCVOnline/CreateCVOnline/Controllers/CandidateController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using CreateCVOnline.Models;
using CreateCVOnline.Code;
using System.IO;
namespace CreateCVOnline.Controllers
{
    public class CandidateController : Controller
    {
        UserProcess user = new UserProcess();
        // GET: Candidate
        public ActionResult Index()
        {
            var account = Session["Account"] as LoginModel;
            DataTable dt=user.getCV(account.Username);
            var model = new CVModel();
            if(dt.Rows.Count==0)
            {
                model.FullName = "0";
                model.Age = 19;
                model.NumberPhone = "0";
                model.Address = "0";
                model.ID_Skills = 1;
                model.Goal = "0";
                model.Email = "0";
                model.Image = "0";
                model.ID_Jobs = 1;
                model.ID_Education = 1;
                model.ID_Activities = 1;
            }
            else
            {
                model.FullName = dt.Rows[0]["Fullname"].ToString();
                model.Age = Convert.ToInt32(dt.Rows[0]["Age"].ToString());
                model.NumberPhone = dt.Rows[0]["Numberphone"].ToString();
                model.Address = dt.Rows[0]["Address"].ToString();
                model.ID_Skills = Convert.ToInt32(dt.Rows[0]["ID_Skills"].ToString());
                model.Goal = dt.Rows[0]["Goal"].ToString();
                model.Email = dt.Rows[0]["Email"].ToString();
                model.Image = dt.Rows[0]["Image"].ToString();
                model.ID_Jobs = Convert.ToInt32(dt.Rows[0]["ID_Jobs"].ToString());
                model.ID_Education = Convert.ToInt32(dt.Rows[0]["ID_Education"].ToString());
                model.ID_Activities = Convert.ToInt32(dt.Rows[0]["ID_Activities"].ToString());
            }
            return View(model);
        }
        [HttpPost]
        public ActionResult Index(string Username)
        {
            /*if (Username == null)
                Username = "phutai001";*/
            DataTable dt = user.getCV(Username);
            var model = new CVModel();
            model.FullName = dt.Rows[0]["Fullname"].ToString();
            model.Age = Convert.ToInt32(dt.Rows[0]["Age"].ToString());
            model.NumberPhone = dt.Rows[0]["Numberphone"].ToString();
            model.Address = dt.Rows[0]["Address"].ToString();
            model.ID_Skills = Convert.ToInt32(dt.Rows[0]["ID_Skills"].ToString());
            model.Goal = dt.Rows[0]["Goal"].ToString();
            model.Email = dt.Rows[0]["Email"].ToString();
            model.Image = dt.Rows[0]["Image"].ToString();
            model.ID_Jobs = Convert.ToInt32(dt.Rows[0]["ID_Jobs"].ToString());
            model.ID_Education = Convert.ToInt32(dt.Rows[0]["ID_Education"].ToString());
            model.ID_Activities = Convert.ToInt32(dt.Rows[0]["ID_Activities"].ToString());
            return View(model);
        }
        public ActionResult EditCV()
        {
            return View();
        }

        [HttpPost]
        public ActionResult EditCV(CVModel cv)
        {
            var account = Session["Account"] as LoginModel;
            user.chinhsua(account.Username,cv.FullName,cv.Email,cv.Age, cv.NumberPhone, cv.Address, cv.Goal);
            return Redirect("/Candidate/Index");
        }
        [HttpPost]
        public ActionResult Upload(HttpPostedFileBase file)
        {
            if (file == null)
            {
                return Redirect("http://google.com");
            }
            string path = "";
            
            path = Path.Combine(Server.MapPath("~/Assets/images"), file.FileName);
            var account = Session["Account"] as LoginModel;
            file.SaveAs(path);
            LoginModel login = Session["Account"] as LoginModel;
            int ID = user.getID(login.Username.ToString());
            user.uploadImage(ID, @"/Assets/images/"+file.FileName);
            return Redirect("/Candidate/Index");
        }

        public ActionResult EditCVDetail()
        {
            return View();
        }
        
        public ActionResult Skills()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Skills(SkillsModel skill)
        {
            LoginModel login = Session["Account"] as LoginModel;
            skill.IDSk = user.getID(login.Username.ToString());
            user.addNewSkill(skill);
            return View();
        }

        public ActionResult Activities()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Activities(ActivitiesModel activities)
        {
            LoginModel login = Session["Account"] as LoginModel;
            activities.ID = user.getID(login.Username.ToString());
            user.addNewActivities(activities);
            return View();
        }

        public ActionResult Jobs()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Jobs(JobsModel jobs)
        {
            LoginModel login = Session["Account"] as LoginModel;
            jobs.ID_Job = user.getID(login.Username.ToString());
            user.addNewJob(jobs);
            return View();
        }

        public ActionResult Education()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Education(EducationModel edu)
        {
            LoginModel login = Session["Account"] as LoginModel;
            edu.IDEdu = user.getID(login.Username.ToString());
            user.addNewEducation(edu);
            return View();
        }
    }
}

CreateCVOnline/CreateCVOnline/Views/Candidate/Activities.cshtml
@model CreateCVOnline.Models.ActivitiesModel

@{
    ViewBag.Title = "Activities";
    Layout = "~/Views/Shared/_LayoutCreateCVOnline.cshtml";
}

<h2>Activities</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ActivitiesModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.ActivitiesDetail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ActivitiesDetail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ActivitiesDetail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Add New Activities" class="btn btn-success" />
            </div>
        </div>
    </div>
}

CreateCVOnline/CreateCVOnline/Views/Candidate/Download.cshtml
@{
    ViewBag.Title = "Download";
    Layout = "~/Views/Shared/_LayoutCreateCVOnline.cshtml";
}

<h2>Download</h2>

CreateCVOnline/CreateCVOnline/Views/Candidate/EditCV.cshtml
@model CreateCVOnline.Models.CVModel

@{
    ViewBag.Title = "EditCV";
    Layout = "~/Views/Shared/_LayoutCreateCVOnline.cshtml";
}
    <style>

        /* style glyph */
        .inner-addon .glyphicon {
            position: absolute;
            padding: 10px;
            pointer-events: none;
        }


        /* add padding  */
        .left-addon input {
            padding-left: 30px;
        }
    </style>
<br />
@using(Html.BeginForm("Upload","Candidate",FormMethod.Post,new { enctype="multipart/form-data"}))
{
    <h3>Upload Avatar</h3>
    <input type="file" name="file" value="Browse"/>
    <input type="submit" value="UploaImage" />
}
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

<div class="form-group">
    
</div>
    <div class="form-group">
        @Html.LabelFor(model => model.FullName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10 inner-addon left-addon">
            <i class="glyphicon glyphicon-user"></i>
            @Html.EditorFor(model => model.FullName, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Full Name" }, @style = "width:800px" })
            @Html.ValidationMessageFor(model => model.FullName, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10 inner-addon left-addon">
            <i class="glyphicon glyphicon-envelope"></i>
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Email" }, @style = "width:800px" })
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>
    </div>



    <div class="form-group">
        @Html.LabelFor(model => model.Age, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10 inner-addon left-addon">
            <i class="glyphicon glyphicon-calendar"></i>
            @Html.EditorFor(model => model.Age, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Age" }, @style = "width:800px" })
            @Html.ValidationMessageFor(model => model.Age, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.NumberPhone, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10 inner-addon left-addon">
            <i class="glyphicon glyphicon-earphone"></i>
            @Html.EditorFor(model => model.NumberPhone, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Numberphone" }, @style = "width:800px" })
            @Html.ValidationMessageFor(model => model.NumberPhone, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10 inner-addon left-addon">
            <i class="glyphicon glyphicon-road"></i>
            @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Address" }, @style = "width:1200px" })
            @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
        </div>
    </div>



    <div class="form-group">
        @Html.LabelFor(model => model.Goal, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10 inner-addon left-addon">
            <i class="glyphicon glyphicon-list-alt"></i>
            @Html.TextAreaFor(model => model.Goal, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Goal And Your Vision" }, @style = "width:1200px; height:200px " })
            @Html.ValidationMessageFor(model => model.Goal, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-success" style="width:200px" />
        </div>
    </div>
</div>
}

CreateCVOnline/CreateCVOnline/Views/Candidate/EditCVDetail.cshtml
@model CreateCVOnline.Models.SkillsModel
@{
    ViewBag.Title = "Edit CV Detail";
    Layout = "~/Views/Shared/_LayoutCreateCVOnline.cshtml";
}

<!DOCUMENT html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Login Form</title>
    <!-- Import Bootstrap and JQuery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js">
    </script>
    <link rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js">
    </script>
    <!-- My CSS and JQuery -->
    <link href="~/Assets/css/main.css" rel="stylesheet">
    <script type="text/javascript" src="~/Assets/jquery/editcv.js"></script>
</head>
<body>
    
</body>
</html>

CreateCVOnline/CreateCVOnline/Views/Candidate/EditCVs.cshtml
@{
    Layout = "~/Views/Shared/_LayoutCreateCVOnline.cshtml";
}

CreateCVOnline/CreateCVOnline/Views/Candidate/Education.cshtml
@model CreateCVOnline.Models.EducationModel

@{
    ViewBag.Title = "Education";
    Layout = "~/Views/Shared/_LayoutCreateCVOnline.cshtml";
}

<h2>Education</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>EducationModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.EducationDetail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EducationDetail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EducationDetail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Time, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Time, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Time, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Type, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Add New Education" class="btn btn-success" />
            </div>
        </div>
    </div>
}

CreateCVOnline/CreateCVOnline/Views/Candidate/Jobs.cshtml
@model CreateCVOnline.Models.JobsModel

@{
    ViewBag.Title = "Jobs";
    Layout = "~/Views/Shared/_LayoutCreateCVOnline.cshtml";
}

<h2>Jobs</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>JobsModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.JobsDetail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.JobsDetail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.JobsDetail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Time, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Time, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Time, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Type, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Add New Job" class="btn btn-success" />
            </div>
        </div>
    </div>
}

CreateCVOnline/CreateCVOnline/Views/Candidate/Skills.cshtml
@model CreateCVOnline.Models.SkillsModel
@using CreateCVOnline.Code
@using CreateCVOnline.Models
@{
    ViewBag.Title = "Skills";
    Layout = "~/Views/Shared/_LayoutCreateCVOnline.cshtml";
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        <hr />
        <hr />

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">

            @Html.LabelFor(model => model.SkillsName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SkillsName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SkillsName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Percent, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Percent, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Percent, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Add New Skill" class="btn btn-success" />
            </div>
        </div>
    </div>
}