CreateCVOnline/CreateCVOnline/Controllers/LandingPageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CreateCVOnline.Controllers
{
    public class LandingPageController : Controller
    {
        // GET: LandingPage
        public ActionResult Index()
        {
            return View();
        }

        // GET: HeaderPage
        public ActionResult Header()
        {
            return View();
        }
    }
}

CreateCVOnline/CreateCVOnline/Views/Shared/Header.cshtml
@using System.Web
@using CreateCVOnline.Models
@using CreateCVOnline.Code
@{
    UserProcess usr = new UserProcess();
    var user = Session["Account"] as LoginModel;
}
@if (user == null)
{
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="container">
            <a class="navbar-brand" href="#">Create CV Online</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="#">
                            Home
                            <span class="sr-only">(current)</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/Account/Login">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/Account/Register">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Contact</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
}
else
{
    var username = user.Username;
    var role = usr.getRole(username);
    if (role == 1)
    {
        <!-- Navigation -->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
            <div class="container">
                <a class="navbar-brand" href="#">Create CV Online</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item active">
                            <a class="nav-link" href="#">
                                Home
                                <span class="sr-only">(current)</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="">Hi @user.Username</a>
                        </li>
                        <li class="nav-item">
                            <a href="/Candidate/Index" class="nav-link">CV</a>
                        </li>
                        <li class="nav-item">
                            <a href="/Candidate/Skills" class="nav-link">Skills</a>
                        </li>
                        <li class="nav-item">
                            <a href="/Candidate/Activities" class="nav-link">Activities</a>
                        </li>
                        <li class="nav-item">
                            <a href="/Candidate/Education" class="nav-link">Education</a>
                        </li>
                        <li class="nav-item">
                            <a href="/Candidate/Jobs" class="nav-link">Jobs</a>
                        </li>
                        <li class="nav-item">
                            <a href="/Candidate/EditCV" class="nav-link">Change CV Profile</a>
                        </li>
                        <li class="nav-item">
                            <a href="/Account/ChangePassword" class="nav-link">Change Password</a>
                        </li>
                        <li class="nav-item">
                            <a href="/Account/Logout" class="nav-link">Logout</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    }
    else if (role == 0)
    {
        <!-- Navigation -->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
            <div class="container">
                <a class="navbar-brand" href="#">Create CV Online</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item active">
                            <a class="nav-link" href="#">
                                Home
                                <span class="sr-only">(current)</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="">Hi @user.Username</a>
                        </li>
                        <li class="nav-item">
                            <a href="/Business/Index" class="nav-link">List Candidate</a>
                        </li>
                        <li class="nav-item">
                            <a href="/Account/ChangePassword" class="nav-link">Change Password</a>
                        </li>
                        <li class="nav-item">
                            <a href="/Account/Logout" class="nav-link">Logout</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    }

}

CreateCVOnline/CreateCVOnline/Views/Shared/_LayoutCreateCVOnline.cshtml
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Create CV Online </title>

    <!-- Bootstrap core CSS -->
    <link href="~/Content/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="~/Content/heroic-features.css" rel="stylesheet">
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

</head>

<body>

    @{Html.RenderAction("Header", "LandingPage");} 

    @RenderBody()
    <!-- /.container -->
    <!-- Footer -->
    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; Your Website 2020</p>
        </div>
        <!-- /.container -->
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="~/Scripts/jquery.min.js"></script>
    <script src="~/Scripts/bootstrap.bundle.min.js"></script>

</body>

</html>