CreateCVOnline/CreateCVOnline/Controllers/AccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CreateCVOnline.Models;
using CreateCVOnline.Code;
using CaptchaMvc.HtmlHelpers;
namespace CreateCVOnline.Controllers
{
    public class AccountController : Controller
    {
        private String GetMD5(string txt)
        {
            String str = "";
            Byte[] buffer = System.Text.Encoding.UTF8.GetBytes(txt);
            System.Security.Cryptography.MD5CryptoServiceProvider md5 = new System.Security.Cryptography.MD5CryptoServiceProvider();
            buffer = md5.ComputeHash(buffer);
            foreach (Byte b in buffer)
            {
                str += b.ToString("X2");
            }
            return str;
        }
        UserProcess user = new UserProcess();
        // GET: Login
        public ActionResult Login()
        {
            return View();
        }
        //Post: Login
        [HttpPost]
        public ActionResult Login(LoginModel login)
        {
            if(!this.IsCaptchaValid(""))
            {
                return Redirect("/Account/Login");
            }
            login.Password = GetMD5(login.Password);
            if (user.checkLogin(login))
            {
                Session.Add("Account", login);
                int k = user.getRole(login.Username);
                int firsttime = user.getIsFirstTime(login.Username);
                if (k == 1)
                    if (firsttime == 0)
                        return Redirect("/Candidate/Index");
                    else
                        return Redirect("/Candidate/EditCV");
                else if (k == 0)
                    return Redirect("/Business/Index");
                else
                    return Redirect("/AdminPage/Index");
            }
            return View();
        }
       //Get: Register
        public  ActionResult Register()
        {
            return View();
        }

        //Post: Register
        [HttpPost]
        public ActionResult Register(RegisterModel register)
        {

            register.Password = GetMD5(register.Password);
            if (user.register(register))
                return Redirect("/Account/Login");
            return View();
        }

        //Get: ChangePassword
        public ActionResult ChangePassword()
        {
            return View();
        }

        //Post: ChangePassword
        [HttpPost]
        public ActionResult ChangePassword(ChangePasswordModel changePassword)
        {
            changePassword.Password = GetMD5(changePassword.Password);
            user.changepassword(changePassword);
            return View();
        }

        public ActionResult Logout()
        {
            Session["Account"] = null;
            return Redirect("/LandingPage/Index");
        }

        //GET: Edit CV Detail
        public ActionResult EditCVDetail()
        {
            return View();
        }
        public ActionResult contact()
        {
            return View();
        }
    }
}

CreateCVOnline/CreateCVOnline/Controllers/AdminPageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CreateCVOnline.Code;
using CreateCVOnline.Models;
namespace CreateCVOnline.Controllers
{
    
    public class AdminPageController : Controller
    {
        private String GetMD5(string txt)
        {
            String str = "";
            Byte[] buffer = System.Text.Encoding.UTF8.GetBytes(txt);
            System.Security.Cryptography.MD5CryptoServiceProvider md5 = new System.Security.Cryptography.MD5CryptoServiceProvider();
            buffer = md5.ComputeHash(buffer);
            foreach (Byte b in buffer)
            {
                str += b.ToString("X2");
            }
            return str;
        }
        UserProcess user = new UserProcess();
        // GET: AdminPage
        public ActionResult Index()
        {
            return View();
        }

        //GET: Account General

        public ActionResult Accounts()
        {
            return View();
        }

        //GET: Add New Account
        public ActionResult NewAccount()
        {
            return View();
        }

        //POST: Add New Account
        [HttpPost]
        public ActionResult NewAccount(AccountModel account)
        {
            account.Password = GetMD5(account.Password);
            user.addNewAccount(account);
            return View();
        }

        //GET: Edit Account
        public ActionResult Edit(int id)
        {
            AdminEditAccountModel account=new AdminEditAccountModel();
            account.ID = id.ToString();
            return View(account);
        }
        //Post: Edit Account
        [HttpPost]
        public ActionResult Edit(AdminEditAccountModel account)
        {
            account.Password = GetMD5(account.Password);
            user.adminEditAccount(account);
            return Redirect("/AdminPage/Accounts");
        }

        public ActionResult deleteAccount(int id)
        {
            user.removeAccount(id);
            return Redirect("/AdminPage/Accounts");
        }
    }
}

CreateCVOnline/CreateCVOnline/Views/AdminPage/Accounts.cshtml
@model IEnumerable<CreateCVOnline.Models.Candidate>
@using CreateCVOnline.Code
@using System.Data
@{
    UserProcess usrp = new UserProcess();
    ViewBag.Title = "Accounts";
    Layout = "~/Views/Shared/_AdminLayoutPage1.cshtml";
    DataTable accounts = usrp.getAccount();
}

<h2>Accounts</h2>

<p>
    @Html.ActionLink("Create New", "NewAccount")
</p>
<table class="table">
    <tr>
        <th>
            ID
        </th>
        <th>
            Username
        </th>
        <th>
            Password
        </th>
        <th>
            Role
        </th>
        <th>
            Email
        </th>
        <th></th>
    </tr>

@foreach (DataRow item in accounts.Rows) {
<tr>
    <td>
        @item["ID"]
    </td>
    <td>
        @item["Username"]
    </td>
    <td>
        @item["Password"]
    </td>
    <td>
        @item["Role"]
    </td>
    <td>
        @item["Email"]
    </td>
    <td>
        @Html.ActionLink("Edit", "Edit", new { id=Convert.ToInt32(item["ID"].ToString()) }) |
        @Html.ActionLink("Details", "Details", new { id=Convert.ToInt32(item["ID"].ToString())}) |
        @Html.ActionLink("Delete", "deleteAccount", new { id=Convert.ToInt32(item["ID"].ToString()) })
    </td>
</tr>
}

</table>

CreateCVOnline/CreateCVOnline/Views/AdminPage/Edit.cshtml
@model CreateCVOnline.Models.AdminEditAccountModel
@using CreateCVOnline.Code;
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_AdminLayoutPage1.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit","AdminPage",FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Edit Account Model</h4>
        <hr />
        ID:   @Model.ID
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)
        
        <div class="form-group">
            @Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Role, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Role, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Role, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

CreateCVOnline/CreateCVOnline/Views/AdminPage/NewAccount.cshtml
@model CreateCVOnline.Models.AccountModel
@{
    
    ViewBag.Title = "NewAccount";
    Layout = "~/Views/Shared/_AdminLayoutPage1.cshtml";
}

<h2>NewAccount</h2>

@using (Html.BeginForm("NewAccount","AdminPage",FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>AccountModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Role, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Role, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Role, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>